---
title: "Disciplina de Ecologia Numérica"
subtitle: "Disciplina de Ecologia Numérica, Bacharelado em Ciências Biológicas Campus V - UEPB"
author: 
  - Prof. Elvio S. F. Medeiros  
  - Laboratório de Ecologia
  - Universidade Estadual da Paraíba
  - Campus V, João Pessoa, PB
date: "`r Sys.Date()`"
abstract: ""
page-layout: full
lang: "pt-br"
editor: source
toc: true
number-sections: true
bibliography: D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/3.R_Quarto/my_references-x9.bib
csl: D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/3.R_Quarto/ecology.csl
highlight-style: pygments
format:
  html:
    code-fold: false
    code-overflow: scroll
    embed-resources: true
  pdf:
    lof: true
    lot: true
    toc: true
    code-line-numbers: true
    colorlinks: true
  docx: default
execute:
  echo: true
always_allow_html: yes
editor_options: 
  chunk_output_type: console
---

# Apresentação

Este é um site experimental da disciplina de graduação de Ecologia Numérica do Curso de Ciências Biológicas da Universidade Estadual da Paraíba.

O site experimental da disciplina de Ecologia Numérica da UEPB é uma plataforma criada com o objetivo de apresentar exemplos didáticos aos alunos, explorando diferentes conceitos e técnicas utilizadas na análise de dados em Ecologia. É importante destacar que os exemplos apresentados no site podem conter imprecisões ou códigos demasiado extensos (aparentemente desnecessários para um ecólogo e programador de R mais experiente), mas isso é proposital, pois a finalidade é oferecer um material didático para os alunos, que possa facilitar a compreensão dos conceitos abordados durante as aulas. Dessa forma, o site é uma ferramenta complementar às aulas presenciais, que busca fornecer exemplos práticos e didáticos para os estudantes de Ecologia Numérica da UEPB.

Como mencionado, a finalidade é didatica e de apresentar o tema seguindo passo-a-passoa e contextualizando com dados ecológicos reais. Por isso, além das informações sobre o conteúdo do site experimental da disciplina de ecologia numérica da UEPB, é importante destacar que qualquer erro ou problema relacionado ao site pode ser reportado ao responsável através do email:

É fundamental que os usuários do site compreendam que plágio e outras formas de má conduta acadêmica são inaceitáveis e podem ter sérias consequências. O responsável pelo site se compromete a remover qualquer conteúdo ofensivo ou sem a devida fonte consultada, que possa ter sido publicado erroneamente ou por engano.
